In [1]:
# 1.Create a NumPy array representing the number of likes on 7 Instagram posts and print its ndim, shape, size, dtype, itemsize, and nbytes properties.

import numpy as np

# Likes on 7 Instagram posts
likes = np.array([120, 250, 180, 340, 500, 275, 410])

print("Instagram Likes:", likes)

print("Number of dimensions (ndim):", likes.ndim)
print("Shape:", likes.shape)
print("Number of elements (size):", likes.size)
print("Data type (dtype):", likes.dtype)
print("Size of each element (itemsize):", likes.itemsize, "bytes")
print("Total memory (nbytes):", likes.nbytes, "bytes")


Instagram Likes: [120 250 180 340 500 275 410]
Number of dimensions (ndim): 1
Shape: (7,)
Number of elements (size): 7
Data type (dtype): int64
Size of each element (itemsize): 8 bytes
Total memory (nbytes): 56 bytes


In [2]:
# 2.Given a 2D NumPy array of daily step counts for 5 days (each row is a day, columns are morning and evening), use reshape() to convert it into a 1D array, then back to a 2D array with 5 rows and 2 columns.<br><br><em><strong>Hint:</strong> Use the shape attribute to check your array after each reshape.</em>

import numpy as np

# Daily steps: 5 days × 2 values
steps = np.array([
    [3000, 4000],
    [3500, 4500],
    [2500, 5000],
    [4000, 4500],
    [3200, 4800]
])

print("Original Array:")
print(steps)

print("Original Shape:", steps.shape)


steps_1d = steps.reshape(10)

print("\n1D Array:")
print(steps_1d)

print("1D Shape:", steps_1d.shape)


steps_2d = steps_1d.reshape(5, 2)

print("\nBack to 2D Array:")
print(steps_2d)

print("2D Shape:", steps_2d.shape)

Original Array:
[[3000 4000]
 [3500 4500]
 [2500 5000]
 [4000 4500]
 [3200 4800]]
Original Shape: (5, 2)

1D Array:
[3000 4000 3500 4500 2500 5000 4000 4500 3200 4800]
1D Shape: (10,)

Back to 2D Array:
[[3000 4000]
 [3500 4500]
 [2500 5000]
 [4000 4500]
 [3200 4800]]
2D Shape: (5, 2)


In [4]:
# 3.Build a NumPy array representing the prices of 12 food items from a Zomato order, then use ravel(), flatten(), and resize() to create different shaped versions of the data and print each result.<br><br><em><strong>Constraint:</strong> Show the difference between ravel() and flatten() in your code comments.</em>

import numpy as np


prices = np.array([
    120, 250, 180, 300,
    150, 220, 350, 175,
    280, 190, 400, 130
])

print("Original Prices:")
print(prices)


prices_2d = prices.reshape(3, 4)

print("\n2D Prices:")
print(prices_2d)


ravel_prices = prices_2d.ravel()

print("\nUsing ravel():")
print(ravel_prices)


flatten_prices = prices_2d.flatten()

print("\nUsing flatten():")
print(flatten_prices)


resized_prices = np.resize(prices_2d, (4, 3))

print("\nUsing resize():")
print(resized_prices)

Original Prices:
[120 250 180 300 150 220 350 175 280 190 400 130]

2D Prices:
[[120 250 180 300]
 [150 220 350 175]
 [280 190 400 130]]

Using ravel():
[120 250 180 300 150 220 350 175 280 190 400 130]

Using flatten():
[120 250 180 300 150 220 350 175 280 190 400 130]

Using resize():
[[120 250 180]
 [300 150 220]
 [350 175 280]
 [190 400 130]]


In [ ]:
# 4.Take a 3x3 NumPy array representing a mini Spotify playlist grid (rows: playlists, columns: song counts in categories like Pop, Rock, Indie). Use both T and np.transpose() to swap rows and columns, then print the transposed array.

import numpy as np


playlist = np.array([
    [25, 15, 10],
    [30, 20, 12],
    [18, 25, 20]
])

print("Original Playlist Grid:")
print(playlist)


transpose_T = playlist.T

print("\nTranspose using T:")
print(transpose_T)


transpose_function = np.transpose(playlist)

print("\nTranspose using np.transpose():")
print(transpose_function)

Original Playlist Grid:
[[25 15 10]
 [30 20 12]
 [18 25 20]]

Transpose using T:
[[25 30 18]
 [15 20 25]
 [10 12 20]]

Transpose using np.transpose():
[[25 30 18]
 [15 20 25]
 [10 12 20]]


In [ ]:
# 5.Given a 1D NumPy array of 15 Flipkart product ratings, use reshape() to convert it into a 3x5 array, then use flatten() to return it to a 1D array. Explain in a comment when you would use flatten() versus ravel() in real projects.

import numpy as np


ratings = np.array([
    5, 4, 3, 5, 4,
    2, 5, 4, 3, 5,
    4, 5, 3, 4, 5
])

print("Original 1D Ratings:")
print(ratings)

print("Original Shape:", ratings.shape)


ratings_2d = ratings.reshape(3, 5)

print("\n3x5 Ratings:")
print(ratings_2d)

print("Shape:", ratings_2d.shape)


ratings_1d = ratings_2d.flatten()

print("\nBack to 1D using flatten():")
print(ratings_1d)

print("Shape:", ratings_1d.shape)



Original 1D Ratings:
[5 4 3 5 4 2 5 4 3 5 4 5 3 4 5]
Original Shape: (15,)

3x5 Ratings:
[[5 4 3 5 4]
 [2 5 4 3 5]
 [4 5 3 4 5]]
Shape: (3, 5)

Back to 1D using flatten():
[5 4 3 5 4 2 5 4 3 5 4 5 3 4 5]
Shape: (15,)
