In [1]:
# 1.Given a NumPy array of IPL team names with some duplicates, use np.unique() to print a sorted list of all unique team names.

import numpy as np

teams = np.array([
    "CSK", "MI", "RCB", "CSK", "KKR",
    "MI", "GT", "RCB", "GT", "PBKS"
])

unique_teams = np.unique(teams)

print("Unique IPL Teams:")
print(unique_teams)


Unique IPL Teams:
['CSK' 'GT' 'KKR' 'MI' 'PBKS' 'RCB']


In [2]:
# 2.Create a NumPy array of Zomato order ratings (with some NaN values), then use np.isnan() to count how many ratings are missing.

import numpy as np

ratings = np.array([4.5, 4.2, np.nan, 3.8, np.nan, 4.7, 4.0, np.nan])

missing_values = np.isnan(ratings)
missing_count = np.sum(missing_values)

print("Zomato Ratings:")
print(ratings)

print("Missing Ratings:")
print(missing_values)

print("Number of Missing Ratings:", missing_count)

Zomato Ratings:
[4.5 4.2 nan 3.8 nan 4.7 4.  nan]
Missing Ratings:
[False False  True False  True False False  True]
Number of Missing Ratings: 3


In [3]:
# 3.Given an array of Flipkart product prices, use np.clip() to limit all prices between 100 and 1000, and print the resulting array.<br><br><em><strong>Hint:</strong> Use np.clip(array, 100, 1000).</em>

import numpy as np

prices = np.array([50, 150, 450, 750, 1200, 2500, 80, 900])

clipped_prices = np.clip(prices, 100, 1000)

print("Original Prices:")
print(prices)

print("Clipped Prices:")
print(clipped_prices)

Original Prices:
[  50  150  450  750 1200 2500   80  900]
Clipped Prices:
[ 100  150  450  750 1000 1000  100  900]


In [4]:
# 4.You have a NumPy array of YouTube video view counts, some of which are NaN or inf. Replace all NaN values with 0, and all inf values with the maximum finite value in the array.

import numpy as np

views = np.array([
    10000, 25000, np.nan, 50000,
    np.inf, 35000, np.nan, 45000,
    np.inf
])

finite_values = views[np.isfinite(views)]
max_finite_value = np.max(finite_values)

cleaned_views = np.nan_to_num(
    views,
    nan=0,
    posinf=max_finite_value,
    neginf=max_finite_value
)

print("Original Views:")
print(views)

print("Maximum Finite Value:", max_finite_value)

print("Cleaned Views:")
print(cleaned_views)

Original Views:
[10000. 25000.    nan 50000.    inf 35000.    nan 45000.    inf]
Maximum Finite Value: 50000.0
Cleaned Views:
[10000. 25000.     0. 50000. 50000. 35000.     0. 45000. 50000.]


In [5]:
# 5.Use ChatGPT to generate a Python code snippet that finds the indices of all even numbers in a NumPy array using np.where(), then test the code with your own example array.


import numpy as np

numbers = np.array([11, 24, 35, 42, 57, 68, 73, 80, 91, 100])

even_indices = np.where(numbers % 2 == 0)

print("Array:")
print(numbers)

print("Indices of Even Numbers:")
print(even_indices[0])

Array:
[ 11  24  35  42  57  68  73  80  91 100]
Indices of Even Numbers:
[1 3 5 7 9]
