In [1]:
# 1.Create a NumPy array called prices with the following values: [199, 299, 399, 499, 599]. Use basic indexing to print the first and last price.

import numpy as np

prices = np.array([199, 299, 399, 499, 599])

print("First Price:", prices[0])
print("Last Price:", prices[-1])


First Price: 199
Last Price: 599


In [2]:
# 2.Given a 2D NumPy array representing cricket scores for 3 players across 5 matches, use slicing to extract the scores of all players for matches 2 to 4 (index 1 to 3).

import numpy as np

scores = np.array([
    [45, 60, 72, 80, 55],
    [50, 65, 70, 85, 60],
    [40, 55, 68, 75, 50]
])

result = scores[:, 1:4]

print("Original Scores:")
print(scores)

print("\nScores for Matches 2 to 4:")
print(result)

Original Scores:
[[45 60 72 80 55]
 [50 65 70 85 60]
 [40 55 68 75 50]]

Scores for Matches 2 to 4:
[[60 72 80]
 [65 70 85]
 [55 68 75]]


In [3]:
# 3.You have a NumPy array called ratings = np.array([4.5, 3.8, 4.2, 2.9, 5.0, 3.5]). Use negative indexing to print the last three ratings.

import numpy as np

ratings = np.array([4.5, 3.8, 4.2, 2.9, 5.0, 3.5])

last_three = ratings[-3:]

print("Last Three Ratings:", last_three)

Last Three Ratings: [2.9 5.  3.5]


In [ ]:
# 4.Create a NumPy array of the first 20 natural numbers. Use step slicing to print every 3rd number starting from the second element.<br><br><em><strong>Hint:</strong> Use the slice notation with a step value.</em>

import numpy as np

numbers = np.arange(1, 21)

result = numbers[1::3]

print("Natural Numbers:")
print(numbers)

print("\nEvery 3rd Number Starting from Second Element:")
print(result)

In [4]:
# 5.Given a NumPy array of Flipkart product prices, use boolean indexing to extract all prices greater than 500. Print the resulting array.

import numpy as np

prices = np.array([250, 650, 450, 800, 350, 1200, 550, 499])

result = prices[prices > 500]

print("Product Prices:", prices)
print("Prices Greater Than 500:", result)

Product Prices: [ 250  650  450  800  350 1200  550  499]
Prices Greater Than 500: [ 650  800 1200  550]


In [5]:
# 6.You have an array of IPL team scores: np.array([210, 180, 195, 220, 205, 175]). Use np.where() to find the indices of all scores above 200 and print these indices.

import numpy as np

scores = np.array([210, 180, 195, 220, 205, 175])

indices = np.where(scores > 200)

print("IPL Scores:", scores)
print("Indices of Scores Above 200:", indices[0])

IPL Scores: [210 180 195 220 205 175]
Indices of Scores Above 200: [0 3 4]
