In [1]:
# 1.Create two NumPy arrays representing the ratings of 5 restaurants on Zomato and Swiggy, then use np.concatenate() to combine them into a single array of 10 ratings and print the result.

import numpy as np

zomato_ratings = np.array([4.5, 4.2, 3.8, 4.7, 4.0])
swiggy_ratings = np.array([4.1, 3.9, 4.6, 4.3, 4.8])

combined_ratings = np.concatenate((zomato_ratings, swiggy_ratings))

print("Zomato Ratings:", zomato_ratings)
print("Swiggy Ratings:", swiggy_ratings)
print("Combined Ratings:", combined_ratings)


Zomato Ratings: [4.5 4.2 3.8 4.7 4. ]
Swiggy Ratings: [4.1 3.9 4.6 4.3 4.8]
Combined Ratings: [4.5 4.2 3.8 4.7 4.  4.1 3.9 4.6 4.3 4.8]


In [2]:
# 2.Given three arrays representing the number of likes on three different Instagram posts over 7 days, stack them vertically using np.vstack() so that each row represents one post's weekly likes, and print the stacked array.

import numpy as np

post1 = np.array([100, 150, 200, 250, 300, 350, 400])
post2 = np.array([120, 170, 220, 280, 330, 380, 420])
post3 = np.array([90, 140, 190, 240, 290, 340, 390])

weekly_likes = np.vstack((post1, post2, post3))

print("Weekly Likes:")
print(weekly_likes)

Weekly Likes:
[[100 150 200 250 300 350 400]
 [120 170 220 280 330 380 420]
 [ 90 140 190 240 290 340 390]]


In [3]:
# 3.You have an array of 12 Flipkart product IDs. Use np.array_split() to divide this array into 5 nearly equal parts, and display each part.<br><br><em><strong>Hint:</strong> Check the shape of each split to confirm the division.</em>


import numpy as np

product_ids = np.array([
    101, 102, 103, 104,
    105, 106, 107, 108,
    109, 110, 111, 112
])

parts = np.array_split(product_ids, 5)

for i, part in enumerate(parts, start=1):
    print("Part", i, ":", part)
    print("Shape:", part.shape)

Part 1 : [101 102 103]
Shape: (3,)
Part 2 : [104 105 106]
Shape: (3,)
Part 3 : [107 108]
Shape: (2,)
Part 4 : [109 110]
Shape: (2,)
Part 5 : [111 112]
Shape: (2,)


In [4]:
# 4.Simulate a WhatsApp group chat: create a 2D NumPy array where each row is a user and each column is the number of messages sent per day for a week. Use np.insert() to add a new user (row) with their message counts, then use np.delete() to remove the user who sent the least messages overall.

import numpy as np

messages = np.array([
    [20, 25, 30, 15, 22, 28, 35],
    [10, 12, 15, 8, 14, 10, 12],
    [35, 40, 30, 45, 38, 42, 50]
])

new_user = np.array([[25, 30, 28, 35, 32, 40, 45]])

messages = np.insert(messages, 3, new_user, axis=0)

totals = messages.sum(axis=1)

least_user_index = np.argmin(totals)

messages = np.delete(messages, least_user_index, axis=0)

print("Final Group Messages:")
print(messages)

print("Total Messages of Remaining Users:")
print(messages.sum(axis=1))

Final Group Messages:
[[20 25 30 15 22 28 35]
 [35 40 30 45 38 42 50]
 [25 30 28 35 32 40 45]]
Total Messages of Remaining Users:
[175 280 235]


In [5]:
# 5.Given a NumPy array of YouTube video view counts, use .view() to create a view and .copy() to create a copy. Modify the first element in each and print all arrays to demonstrate the difference between view and copy.<br><br><em><strong>Hint:</strong> Observe which changes affect the original array.</em>

import numpy as np

views = np.array([1000, 2000, 3000, 4000, 5000])

view_array = views.view()
copy_array = views.copy()

view_array[0] = 9999
copy_array[0] = 8888

print("Original Array:", views)
print("View Array:", view_array)
print("Copy Array:", copy_array)

Original Array: [9999 2000 3000 4000 5000]
View Array: [9999 2000 3000 4000 5000]
Copy Array: [8888 2000 3000 4000 5000]
